/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ana;

/**
 *
 * @author anddi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        abaInicio = new javax.swing.JPanel();
        panelBestReceitas = new javax.swing.JPanel();
        panelBestVendedores = new javax.swing.JPanel();
        panelBestProdutos = new javax.swing.JPanel();
        btnImportarDados = new javax.swing.JButton();
        abaReceita = new javax.swing.JPanel();
        panelBestReceitas1 = new javax.swing.JPanel();
        panelBestVendedores1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnMaisDetalhesCustos = new javax.swing.JButton();
        btnMaisDetalhesUltimosmeses = new javax.swing.JButton();
        btnDetalhesMetasPorLucro = new javax.swing.JButton();
        abaVendedores = new javax.swing.JPanel();
        panelMetasPorVendasVendedores = new javax.swing.JPanel();
        panelBestVendedoresGeral = new javax.swing.JPanel();
        panelBestVendedoresMes = new javax.swing.JPanel();
        btnMaisDetalhesVendedoresGeral = new javax.swing.JButton();
        btnMaisDetalhesVendedoresMes = new javax.swing.JButton();
        btnMaisDetalhesVendedoresMetasPorVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana");

        abas.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        panelBestReceitas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelBestReceitasLayout = new javax.swing.GroupLayout(panelBestReceitas);
        panelBestReceitas.setLayout(panelBestReceitasLayout);
        panelBestReceitasLayout.setHorizontalGroup(
            panelBestReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestReceitasLayout.setVerticalGroup(
            panelBestReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBestVendedores.setBackground(new java.awt.Color(204, 204, 204));
        panelBestVendedores.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout panelBestVendedoresLayout = new javax.swing.GroupLayout(panelBestVendedores);
        panelBestVendedores.setLayout(panelBestVendedoresLayout);
        panelBestVendedoresLayout.setHorizontalGroup(
            panelBestVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestVendedoresLayout.setVerticalGroup(
            panelBestVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        panelBestProdutos.setBackground(new java.awt.Color(204, 204, 204));
        panelBestProdutos.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout panelBestProdutosLayout = new javax.swing.GroupLayout(panelBestProdutos);
        panelBestProdutos.setLayout(panelBestProdutosLayout);
        panelBestProdutosLayout.setHorizontalGroup(
            panelBestProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestProdutosLayout.setVerticalGroup(
            panelBestProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnImportarDados.setText("Importar Dados");
        btnImportarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaInicioLayout = new javax.swing.GroupLayout(abaInicio);
        abaInicio.setLayout(abaInicioLayout);
        abaInicioLayout.setHorizontalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBestReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelBestVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImportarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBestProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        abaInicioLayout.setVerticalGroup(
            abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBestReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBestVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(panelBestProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnImportarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abas.addTab("Inicio", abaInicio);

        panelBestReceitas1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelBestReceitas1Layout = new javax.swing.GroupLayout(panelBestReceitas1);
        panelBestReceitas1.setLayout(panelBestReceitas1Layout);
        panelBestReceitas1Layout.setHorizontalGroup(
            panelBestReceitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestReceitas1Layout.setVerticalGroup(
            panelBestReceitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBestVendedores1.setBackground(new java.awt.Color(204, 204, 204));
        panelBestVendedores1.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout panelBestVendedores1Layout = new javax.swing.GroupLayout(panelBestVendedores1);
        panelBestVendedores1.setLayout(panelBestVendedores1Layout);
        panelBestVendedores1Layout.setHorizontalGroup(
            panelBestVendedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestVendedores1Layout.setVerticalGroup(
            panelBestVendedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnMaisDetalhesCustos.setText("Mais Detalhes");
        btnMaisDetalhesCustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesCustosActionPerformed(evt);
            }
        });

        btnMaisDetalhesUltimosmeses.setText("Mais Detalhes");
        btnMaisDetalhesUltimosmeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesUltimosmesesActionPerformed(evt);
            }
        });

        btnDetalhesMetasPorLucro.setText("Mais Detalhes");
        btnDetalhesMetasPorLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMetasPorLucroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaReceitaLayout = new javax.swing.GroupLayout(abaReceita);
        abaReceita.setLayout(abaReceitaLayout);
        abaReceitaLayout.setHorizontalGroup(
            abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelBestReceitas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetalhesMetasPorLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelBestVendedores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaisDetalhesCustos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnMaisDetalhesUltimosmeses, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        abaReceitaLayout.setVerticalGroup(
            abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBestReceitas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBestVendedores1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(abaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaisDetalhesCustos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaisDetalhesUltimosmeses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalhesMetasPorLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        abas.addTab("Receita", abaReceita);

        panelMetasPorVendasVendedores.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelMetasPorVendasVendedoresLayout = new javax.swing.GroupLayout(panelMetasPorVendasVendedores);
        panelMetasPorVendasVendedores.setLayout(panelMetasPorVendasVendedoresLayout);
        panelMetasPorVendasVendedoresLayout.setHorizontalGroup(
            panelMetasPorVendasVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelMetasPorVendasVendedoresLayout.setVerticalGroup(
            panelMetasPorVendasVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBestVendedoresGeral.setBackground(new java.awt.Color(204, 204, 204));
        panelBestVendedoresGeral.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout panelBestVendedoresGeralLayout = new javax.swing.GroupLayout(panelBestVendedoresGeral);
        panelBestVendedoresGeral.setLayout(panelBestVendedoresGeralLayout);
        panelBestVendedoresGeralLayout.setHorizontalGroup(
            panelBestVendedoresGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestVendedoresGeralLayout.setVerticalGroup(
            panelBestVendedoresGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        panelBestVendedoresMes.setBackground(new java.awt.Color(204, 204, 204));
        panelBestVendedoresMes.setPreferredSize(new java.awt.Dimension(305, 100));

        javax.swing.GroupLayout panelBestVendedoresMesLayout = new javax.swing.GroupLayout(panelBestVendedoresMes);
        panelBestVendedoresMes.setLayout(panelBestVendedoresMesLayout);
        panelBestVendedoresMesLayout.setHorizontalGroup(
            panelBestVendedoresMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        panelBestVendedoresMesLayout.setVerticalGroup(
            panelBestVendedoresMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnMaisDetalhesVendedoresGeral.setText("Mais Detalhes");
        btnMaisDetalhesVendedoresGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesVendedoresGeralActionPerformed(evt);
            }
        });

        btnMaisDetalhesVendedoresMes.setText("Mais Detalhes");
        btnMaisDetalhesVendedoresMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesVendedoresMesActionPerformed(evt);
            }
        });

        btnMaisDetalhesVendedoresMetasPorVendas.setText("Mais Detalhes");
        btnMaisDetalhesVendedoresMetasPorVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisDetalhesVendedoresMetasPorVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaVendedoresLayout = new javax.swing.GroupLayout(abaVendedores);
        abaVendedores.setLayout(abaVendedoresLayout);
        abaVendedoresLayout.setHorizontalGroup(
            abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelMetasPorVendasVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaisDetalhesVendedoresMetasPorVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelBestVendedoresGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaisDetalhesVendedoresGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnMaisDetalhesVendedoresMes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBestVendedoresMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        abaVendedoresLayout.setVerticalGroup(
            abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMetasPorVendasVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBestVendedoresGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(panelBestVendedoresMes, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(abaVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaisDetalhesVendedoresGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaisDetalhesVendedoresMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaisDetalhesVendedoresMetasPorVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        abas.addTab("Produtos", abaVendedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalhesMetasPorLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMetasPorLucroActionPerformed
        // Gerar janela com gráfico de Meta mensai por lucro mensal de até quando se tem dados:
    }//GEN-LAST:event_btnDetalhesMetasPorLucroActionPerformed

    private void btnMaisDetalhesUltimosmesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesUltimosmesesActionPerformed
        // Gerar janela com gráfico de receita mensal até onde se tem dados:
    }//GEN-LAST:event_btnMaisDetalhesUltimosmesesActionPerformed

    private void btnMaisDetalhesCustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesCustosActionPerformed
        // Gerar janela com gráfico de custos até onde se tem dados:
    }//GEN-LAST:event_btnMaisDetalhesCustosActionPerformed

    private void btnImportarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarDadosActionPerformed
        // Inserir função para importar uma tabela excel aqui:
    }//GEN-LAST:event_btnImportarDadosActionPerformed

    private void btnMaisDetalhesVendedoresGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesVendedoresGeralActionPerformed
        // Gerar janela com gráfico geral dos melhores vendedores:
    }//GEN-LAST:event_btnMaisDetalhesVendedoresGeralActionPerformed

    private void btnMaisDetalhesVendedoresMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesVendedoresMesActionPerformed
        // Gerar janela com gráfico dos vendedores por mês:
    }//GEN-LAST:event_btnMaisDetalhesVendedoresMesActionPerformed

    private void btnMaisDetalhesVendedoresMetasPorVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisDetalhesVendedoresMetasPorVendasActionPerformed
        // Gerar janela com gráfico de meta por venda dos vendedores:
    }//GEN-LAST:event_btnMaisDetalhesVendedoresMetasPorVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaInicio;
    private javax.swing.JPanel abaReceita;
    private javax.swing.JPanel abaVendedores;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnDetalhesMetasPorLucro;
    private javax.swing.JButton btnImportarDados;
    private javax.swing.JButton btnMaisDetalhesCustos;
    private javax.swing.JButton btnMaisDetalhesUltimosmeses;
    private javax.swing.JButton btnMaisDetalhesVendedoresGeral;
    private javax.swing.JButton btnMaisDetalhesVendedoresMes;
    private javax.swing.JButton btnMaisDetalhesVendedoresMetasPorVendas;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelBestProdutos;
    private javax.swing.JPanel panelBestReceitas;
    private javax.swing.JPanel panelBestReceitas1;
    private javax.swing.JPanel panelBestVendedores;
    private javax.swing.JPanel panelBestVendedores1;
    private javax.swing.JPanel panelBestVendedoresGeral;
    private javax.swing.JPanel panelBestVendedoresMes;
    private javax.swing.JPanel panelMetasPorVendasVendedores;
    // End of variables declaration//GEN-END:variables
}
